export const siteOrigin = 'https://local.cloud';

export const expectedSearchRoutes = [
  { path: '/', intent: 'Local Google Cloud runtime' },
  { path: '/docs/', intent: 'LocalCloud quick start' },
  { path: '/services/', intent: 'Local GCP service catalog' },
  { path: '/ai/', intent: 'AI agent guide and LocalCloud AGENTS.md template' },
  { path: '/pricing/', intent: 'LocalCloud free public preview and permitted use' },
  { path: '/ai/agents.md', intent: 'Raw LocalCloud agent execution guide' },
  { path: '/ai/AGENTS.md', intent: 'Downloadable LocalCloud AGENTS.md template' },
  { path: '/ai/resources.md', intent: 'Agent Markdown route index' },
  { path: '/ai/services.md', intent: 'Raw LocalCloud agent service matrix' },
  { path: '/ai/compatibility.md', intent: 'Raw LocalCloud agent compatibility boundaries' },
  { path: '/ai/docs.md', intent: 'Raw LocalCloud agent docs index' },
  { path: '/llms.txt', intent: 'LocalCloud LLM route index' },
  { path: '/llms-full.txt', intent: 'Long-form LocalCloud LLM context' },
  { path: '/gcp-emulator/', intent: 'Run Google Cloud locally' },
  { path: '/localstack-for-google-cloud/', intent: 'LocalStack-style GCP development' },
  { path: '/compatibility/', intent: 'LocalCloud compatibility and limitations' },
  { path: '/gcp-integration-testing/', intent: 'Local GCP integration testing' },
  { path: '/reduce-gcp-dev-costs/', intent: 'Reduce GCP development costs' },
  { path: '/bigquery-emulator/', intent: 'BigQuery emulator' },
  { path: '/bigtable-emulator/', intent: 'Bigtable emulator' },
  { path: '/cloud-storage-emulator/', intent: 'Cloud Storage emulator' },
  { path: '/firestore-emulator/', intent: 'Firestore emulator' },
  { path: '/pubsub-emulator/', intent: 'Pub/Sub emulator' },
  { path: '/spanner-emulator/', intent: 'Spanner emulator' },
  { path: '/local-cloud-for-ai-agents/', intent: 'Local cloud sandbox for AI coding agents' },
  { path: '/compare/', intent: 'LocalCloud alternatives and comparisons' },
  { path: '/compare/localstack/', intent: 'LocalCloud vs LocalStack' },
  { path: '/compare/localgcp/', intent: 'LocalCloud vs localgcp' },
  { path: '/compare/e2b-vercel-sandboxes/', intent: 'LocalCloud vs hosted agent sandboxes' },
  { path: '/agents/', intent: 'Agent sandbox setup routes' },
  { path: '/workflows/', intent: 'Agent and automation workflows' },
  { path: '/glossary/', intent: 'Local cloud and agent glossary' },
  { path: '/glossary/agent-environment/', intent: 'Agent environment definition' },
  { path: '/glossary/cloud-emulator/', intent: 'Cloud emulator definition' },
];
